set_property IOSTANDARD LVCMOS33 [get_ports {EMIO_LED_tri_io[0]}]
set_property PACKAGE_PIN K16 [get_ports {EMIO_LED_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports spi_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_start_0]
set_property PACKAGE_PIN E17 [get_ports spi_cs_n_0]
set_property PACKAGE_PIN D18 [get_ports spi_miso_0]
set_property PACKAGE_PIN A20 [get_ports spi_mosi_0]
set_property PACKAGE_PIN C20 [get_ports spi_start_0]
set_property PACKAGE_PIN D19 [get_ports spi_clk_0]
set_property PACKAGE_PIN J15 [get_ports rst_n_0]
